# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jcastorena/proyectosC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jcastorena/proyectosC/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jcastorena/proyectosC/build/CMakeFiles /home/jcastorena/proyectosC/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jcastorena/proyectosC/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named popen3

# Build rule for target.
popen3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 popen3
.PHONY : popen3

# fast build rule for target.
popen3/fast:
	$(MAKE) -f CMakeFiles/popen3.dir/build.make CMakeFiles/popen3.dir/build
.PHONY : popen3/fast

#=============================================================================
# Target rules for targets named plainpopen

# Build rule for target.
plainpopen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plainpopen
.PHONY : plainpopen

# fast build rule for target.
plainpopen/fast:
	$(MAKE) -f CMakeFiles/plainpopen.dir/build.make CMakeFiles/plainpopen.dir/build
.PHONY : plainpopen/fast

#=============================================================================
# Target rules for targets named testprog

# Build rule for target.
testprog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testprog
.PHONY : testprog

# fast build rule for target.
testprog/fast:
	$(MAKE) -f CMakeFiles/testprog.dir/build.make CMakeFiles/testprog.dir/build
.PHONY : testprog/fast

#=============================================================================
# Target rules for targets named dumy

# Build rule for target.
dumy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dumy
.PHONY : dumy

# fast build rule for target.
dumy/fast:
	$(MAKE) -f CMakeFiles/dumy.dir/build.make CMakeFiles/dumy.dir/build
.PHONY : dumy/fast

#=============================================================================
# Target rules for targets named pipes

# Build rule for target.
pipes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pipes
.PHONY : pipes

# fast build rule for target.
pipes/fast:
	$(MAKE) -f CMakeFiles/pipes.dir/build.make CMakeFiles/pipes.dir/build
.PHONY : pipes/fast

dumy.o: dumy.c.o

.PHONY : dumy.o

# target to build an object file
dumy.c.o:
	$(MAKE) -f CMakeFiles/dumy.dir/build.make CMakeFiles/dumy.dir/dumy.c.o
.PHONY : dumy.c.o

dumy.i: dumy.c.i

.PHONY : dumy.i

# target to preprocess a source file
dumy.c.i:
	$(MAKE) -f CMakeFiles/dumy.dir/build.make CMakeFiles/dumy.dir/dumy.c.i
.PHONY : dumy.c.i

dumy.s: dumy.c.s

.PHONY : dumy.s

# target to generate assembly for a file
dumy.c.s:
	$(MAKE) -f CMakeFiles/dumy.dir/build.make CMakeFiles/dumy.dir/dumy.c.s
.PHONY : dumy.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/pipes.dir/build.make CMakeFiles/pipes.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/pipes.dir/build.make CMakeFiles/pipes.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/pipes.dir/build.make CMakeFiles/pipes.dir/main.c.s
.PHONY : main.c.s

plainpopenex.o: plainpopenex.c.o

.PHONY : plainpopenex.o

# target to build an object file
plainpopenex.c.o:
	$(MAKE) -f CMakeFiles/plainpopen.dir/build.make CMakeFiles/plainpopen.dir/plainpopenex.c.o
.PHONY : plainpopenex.c.o

plainpopenex.i: plainpopenex.c.i

.PHONY : plainpopenex.i

# target to preprocess a source file
plainpopenex.c.i:
	$(MAKE) -f CMakeFiles/plainpopen.dir/build.make CMakeFiles/plainpopen.dir/plainpopenex.c.i
.PHONY : plainpopenex.c.i

plainpopenex.s: plainpopenex.c.s

.PHONY : plainpopenex.s

# target to generate assembly for a file
plainpopenex.c.s:
	$(MAKE) -f CMakeFiles/plainpopen.dir/build.make CMakeFiles/plainpopen.dir/plainpopenex.c.s
.PHONY : plainpopenex.c.s

popen3.o: popen3.c.o

.PHONY : popen3.o

# target to build an object file
popen3.c.o:
	$(MAKE) -f CMakeFiles/popen3.dir/build.make CMakeFiles/popen3.dir/popen3.c.o
.PHONY : popen3.c.o

popen3.i: popen3.c.i

.PHONY : popen3.i

# target to preprocess a source file
popen3.c.i:
	$(MAKE) -f CMakeFiles/popen3.dir/build.make CMakeFiles/popen3.dir/popen3.c.i
.PHONY : popen3.c.i

popen3.s: popen3.c.s

.PHONY : popen3.s

# target to generate assembly for a file
popen3.c.s:
	$(MAKE) -f CMakeFiles/popen3.dir/build.make CMakeFiles/popen3.dir/popen3.c.s
.PHONY : popen3.c.s

testprogram.o: testprogram.c.o

.PHONY : testprogram.o

# target to build an object file
testprogram.c.o:
	$(MAKE) -f CMakeFiles/testprog.dir/build.make CMakeFiles/testprog.dir/testprogram.c.o
.PHONY : testprogram.c.o

testprogram.i: testprogram.c.i

.PHONY : testprogram.i

# target to preprocess a source file
testprogram.c.i:
	$(MAKE) -f CMakeFiles/testprog.dir/build.make CMakeFiles/testprog.dir/testprogram.c.i
.PHONY : testprogram.c.i

testprogram.s: testprogram.c.s

.PHONY : testprogram.s

# target to generate assembly for a file
testprogram.c.s:
	$(MAKE) -f CMakeFiles/testprog.dir/build.make CMakeFiles/testprog.dir/testprogram.c.s
.PHONY : testprogram.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... popen3"
	@echo "... plainpopen"
	@echo "... testprog"
	@echo "... dumy"
	@echo "... rebuild_cache"
	@echo "... pipes"
	@echo "... dumy.o"
	@echo "... dumy.i"
	@echo "... dumy.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... plainpopenex.o"
	@echo "... plainpopenex.i"
	@echo "... plainpopenex.s"
	@echo "... popen3.o"
	@echo "... popen3.i"
	@echo "... popen3.s"
	@echo "... testprogram.o"
	@echo "... testprogram.i"
	@echo "... testprogram.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

